package com.myspace.car_come;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InsuranceEventUserData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Need Assistance")
	private boolean needAssistance;

	@org.kie.api.definition.type.Label(value = "Email")
	private java.lang.String email;

	public InsuranceEventUserData() {
	}

	public boolean isNeedAssistance() {
		return this.needAssistance;
	}

	public void setNeedAssistance(boolean needAssistance) {
		this.needAssistance = needAssistance;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public InsuranceEventUserData(boolean needAssistance, java.lang.String email) {
		this.needAssistance = needAssistance;
		this.email = email;
	}

}