package com.myspace.car_come;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class InsuranceEventPoliceCheckResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean isOk;

	public InsuranceEventPoliceCheckResult() {
	}

	public java.lang.Boolean getIsOk() {
		return this.isOk;
	}

	public void setIsOk(java.lang.Boolean isOk) {
		this.isOk = isOk;
	}

	public InsuranceEventPoliceCheckResult(java.lang.Boolean isOk) {
		this.isOk = isOk;
	}

}