package com.myspace.car_come;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InsuranceEventUserData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "First name")
	private java.lang.String firstName;

	@org.kie.api.definition.type.Label(value = "Last name")
	private java.lang.String lastName;

	@org.kie.api.definition.type.Label(value = "Need Assistance")
	private boolean needAssistance;

	public InsuranceEventUserData() {
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public boolean isNeedAssistance() {
		return this.needAssistance;
	}

	public void setNeedAssistance(boolean needAssistance) {
		this.needAssistance = needAssistance;
	}

	public InsuranceEventUserData(java.lang.String firstName,
			java.lang.String lastName, boolean needAssistance) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.needAssistance = needAssistance;
	}

}