package com.myspace.car_come;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class InsuranceEventCarOwner implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public InsuranceEventCarOwner() {
	}

}