package com.myspace.car_come;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RouteData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Address of starting point")
	private java.lang.String addressFrom;
	@org.kie.api.definition.type.Label("Address of destination")
	private java.lang.String addressTo;
	@org.kie.api.definition.type.Label("Departure date and time")
	private java.time.LocalDateTime departure;
	public RouteData() {
	}

	public java.lang.String getAddressFrom() {
		return this.addressFrom;
	}

	public void setAddressFrom(java.lang.String addressFrom) {
		this.addressFrom = addressFrom;
	}

	public java.lang.String getAddressTo() {
		return this.addressTo;
	}

	public void setAddressTo(java.lang.String addressTo) {
		this.addressTo = addressTo;
	}

	public java.time.LocalDateTime getDeparture() {
		return this.departure;
	}

	public void setDeparture(java.time.LocalDateTime departure) {
		this.departure = departure;
	}

	public RouteData(java.lang.String addressFrom, java.lang.String addressTo,
			java.time.LocalDateTime departure) {
		this.addressFrom = addressFrom;
		this.addressTo = addressTo;
		this.departure = departure;
	}

}