package com.myspace.car_come;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class TransportRestResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "ID of found car")
	private java.lang.Integer carID;
	@org.kie.api.definition.type.Label(value = "Transport distance")
	private java.lang.Integer distance;

	public TransportRestResponse() {
	}

	public java.lang.Integer getCarID() {
		return this.carID;
	}

	public void setCarID(java.lang.Integer carID) {
		this.carID = carID;
	}

	public java.lang.Integer getDistance() {
		return this.distance;
	}

	public void setDistance(java.lang.Integer distance) {
		this.distance = distance;
	}

	public TransportRestResponse(java.lang.Integer carID,
			java.lang.Integer distance) {
		this.carID = carID;
		this.distance = distance;
	}

}