package com.myspace.car_come;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class TransportRestResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ID of found car")
	private java.lang.Integer carID;
	@org.kie.api.definition.type.Label("Transport distance")
	private java.lang.Integer distance;

	@org.kie.api.definition.type.Label("Car model")
	private java.lang.String carModel;

	@org.kie.api.definition.type.Label("Price rate")
	private java.lang.Integer rate;

	@org.kie.api.definition.type.Label(value = "Car arrival time")
	private java.time.OffsetDateTime carArrival;

	public TransportRestResponse() {
	}

	public java.lang.Integer getCarID() {
		return this.carID;
	}

	public void setCarID(java.lang.Integer carID) {
		this.carID = carID;
	}

	public java.lang.Integer getDistance() {
		return this.distance;
	}

	public void setDistance(java.lang.Integer distance) {
		this.distance = distance;
	}

	public java.lang.String getCarModel() {
		return this.carModel;
	}

	public void setCarModel(java.lang.String carModel) {
		this.carModel = carModel;
	}

	public java.lang.Integer getRate() {
		return this.rate;
	}

	public void setRate(java.lang.Integer rate) {
		this.rate = rate;
	}

	public java.time.OffsetDateTime getCarArrival() {
		return this.carArrival;
	}

	public void setCarArrival(java.time.OffsetDateTime carArrival) {
		this.carArrival = carArrival;
	}

	public TransportRestResponse(java.lang.Integer carID,
			java.lang.Integer distance, java.lang.String carModel,
			java.lang.Integer rate, java.time.OffsetDateTime carArrival) {
		this.carID = carID;
		this.distance = distance;
		this.carModel = carModel;
		this.rate = rate;
		this.carArrival = carArrival;
	}

}