package com.myspace.car_come;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TransportRequestData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Customer data")
	private java.lang.String customer;
	@org.kie.api.definition.type.Label("Route data")
	private RouteData route;

	public TransportRequestData() {
	}

	public java.lang.String getCustomer() {
		return this.customer;
	}

	public void setCustomer(java.lang.String customer) {
		this.customer = customer;
	}

	public com.myspace.car_come.RouteData getRoute() {
		return this.route;
	}

	public void setRoute(com.myspace.car_come.RouteData route) {
		this.route = route;
	}

	public TransportRequestData(java.lang.String customer,
			com.myspace.car_come.RouteData route) {
		this.customer = customer;
		this.route = route;
	}

}