package com.myspace.car_come;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TransportRate implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TransportRate() {
    }




}