package com.myspace.car_come;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InsuranceEventUserData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("First name")
	private java.lang.String first_name;
	@org.kie.api.definition.type.Label("Last name")
	private java.lang.String last_name;

	@org.kie.api.definition.type.Label("Need Assistance")
	private boolean need_assistance;

	public InsuranceEventUserData() {
	}

	public java.lang.String getFirst_name() {
		return this.first_name;
	}

	public void setFirst_name(java.lang.String first_name) {
		this.first_name = first_name;
	}

	public java.lang.String getLast_name() {
		return this.last_name;
	}

	public void setLast_name(java.lang.String last_name) {
		this.last_name = last_name;
	}

	public boolean isNeed_assistance() {
		return this.need_assistance;
	}

	public void setNeed_assistance(boolean need_assistance) {
		this.need_assistance = need_assistance;
	}

	public InsuranceEventUserData(java.lang.String first_name,
			java.lang.String last_name, boolean need_assistance) {
		this.first_name = first_name;
		this.last_name = last_name;
		this.need_assistance = need_assistance;
	}

}